services:
    app.listener:
        class: AppBundle\Listener\BlameableListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    app.form.extension.novalidate:
        class: AppBundle\Form\Extension\NoValidateExtension
        tags:
            - { name: form.type_extension, alias: form }
    app.datatable.post:
        class: AppBundle\Datatables\PostDatatable
        tags:
            - { name: sg.datatable.view }
