services:
    app.form.extension.novalidate:
        class: AppBundle\Form\Extension\NoValidateExtension
        tags:
            - { name: form.type_extension, alias: form }
    sg_datatables.post:
        class: AppBundle\Datatables\PostDatatable
        tags:
            - { name: sg.datatable.view }
