services:
    app.blameable.listener:
        class: AppBundle\Listener\BlameableListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    app.locale.listener:
        class: AppBundle\Listener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    app.form.extension.novalidate:
        class: AppBundle\Form\Extension\NoValidateExtension
        tags:
            - { name: form.type_extension, alias: form }
    app.datatable.server_side.post:
        class: AppBundle\Datatables\PostDatatable
        tags:
            - { name: sg.datatable.view }
    app.datatable.client_side.post:
        class: AppBundle\Datatables\PostClientSideDatatable
        tags:
            - { name: sg.datatable.view }
